name: Half Hourly News Video Bot

on:
  schedule:
    # Every 30 minutes
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      # (Optional but recommended) Pre-download summarization model
      - name: Pre-download Hugging Face models
        run: |
          python -m transformers.models.bart.convert_bart_original_pytorch_checkpoint_to_pytorch --help || true
          python -c "from transformers import pipeline; pipeline('summarization', model='facebook/bart-large-cnn')"

      - name: Run automation
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
          FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
        run: |
          python src/automation.py

      - name: Upload generated videos
        uses: actions/upload-artifact@v4
        with:
          name: videos
          path: videos/*.mp4
