name: News Full Pipeline Bot


on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install torch

      - name: Download and install ffmpeg
        run: |
          mkdir -p $HOME/bin
          curl -L https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz -o ffmpeg.tar.xz
          tar -xf ffmpeg.tar.xz
          mv ffmpeg-*-amd64-static/ffmpeg $HOME/bin/
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Run automation
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          FACEBOOK_PAGE_ACCESS_TOKEN : ${{ secrets.FACEBOOK_ACCESS_TOKEN  }}
          FACEBOOK_PAGE_ID : ${{ secrets.FACEBOOK_PAGE_ID  }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}

        run: |
          python src/just_video.py

      - name: Upload generated videos data
        uses: actions/upload-artifact@v4
        with:
          name: videos data
          path: data/video_results.json

      - name: Upload generated images
        uses: actions/upload-artifact@v4
        with:
          name: generated-images
          path: images/

      - name: Upload generated videos
        uses: actions/upload-artifact@v4
        with:
          name: generated-videos
          path: output_videos/
