name: Test LLM Hashtag Generation

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/post-text-fb

jobs:
  test-llm-hashtag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install transformers

      - name: Run LLM Hashtag Test
        run: python src/llm_hashtag_test.py
